apiVersion: tor.agabani.co.uk/v1
kind: TorProxy
metadata:
  name: tor-proxy-{{ include "example.fullname" . }}-hpa-external
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  deployment:
    containers:
      tor:
        resources:
          requests:
            cpu: 100m
  service:
    ports:
      - name: http-tunnel
        port: 1080
        protocol: HTTP_TUNNEL
      - name: socks
        port: 9050
        protocol: SOCKS
