apiVersion: tor.agabani.co.uk/v1
kind: OnionBalance
metadata:
  name: onion-balance-{{ include "example.fullname" . }}-deployment
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  deployment:
    securityContext:
      fsGroup: 2000
      runAsGroup: 3000
      runAsUser: 1000
  onionKey:
    name: onion-balance-{{ include "example.fullname" . }}-deployment
  onionServices:
    - onionKey:
        hostname: 3evpjb3a5qxaubnzodlxlgn3ccp3achwwwtirgpznnl752oyg2oxekid.onion
