apiVersion: tor.agabani.co.uk/v1
kind: TorIngress
metadata:
  name: tor-ingress-{{ include "example.fullname" . }}
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  onionBalance:
    onionKey:
      name: tor-ingress-{{ include "example.fullname" . }}
  onionService:
    ports:
      - target: example:80
        virtport: 80
