apiVersion: tor.agabani.co.uk/v1
kind: TorIngress
metadata:
  name: tor-ingress-{{ include "example.fullname" . }}
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  onion_balance:
    onion_key:
      name: tor-ingress-{{ include "example.fullname" . }}
  onion_service:
    ports:
      - target: example:80
        virtport: 80
