version: 2
updates:
  # Maintain dependencies for Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    groups:
      dalek:
        patterns:
          - curve25519-dalek
          - ed25519-dalek
          - x25519-dalek
      kube:
        patterns:
          - kube
          - k8s-openapi
          - schemars
      opentelemetry:
        patterns:
          - opentelemetry
          - opentelemetry-*
          - opentelemetry_*
          - tracing-opentelemetry
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
