site_name: Tor Operator
nav:
  - Tor Operator: 'index.md'
  - Getting Started: 'getting_started.md'
  - CLI: 'cli.md'
  - Container Images: 'container_images.md'
  - Helm: 'helm.md'
  - Custom Resource Definitions:
      - Onion Balance: 'custom_resource_definitions/onion_balance.md'
      - Onion Key: 'custom_resource_definitions/onion_key.md'
      - Onion Service: 'custom_resource_definitions/onion_service.md'
      - Tor Ingress: 'custom_resource_definitions/tor_ingress.md'
  - Security:
      - Cluster Role: 'security/cluster_role.md'
plugins:
  - include-markdown
theme: readthedocs
