nav:
  - Tor Operator: "index.md"
  - Getting Started: "getting_started.md"
  - Changelog: "changelog.md"
  - CLI: "cli.md"
  - Container Images: "container_images.md"
  - Helm: "helm.md"
  - Custom Resource Definitions:
      - OnionBalance: "custom_resource_definitions/onionbalance.md"
      - OnionKey: "custom_resource_definitions/onionkey.md"
      - OnionService: "custom_resource_definitions/onionservice.md"
      - TorIngress: "custom_resource_definitions/toringress.md"
      - TorProxy: "custom_resource_definitions/torproxy.md"
  - Observability:
      - Logs: "observability/logs.md"
      - OpenTelemetry: "observability/opentelemetry.md"
  - Security:
      - Cluster Role: "security/cluster_role.md"
  - Licenses:
      - First Party: "licenses/first_party.md"
      - Third Party: "licenses/third_party.md"
plugins:
  - include-markdown
repo_url: https://github.com/agabani/tor-operator/
site_description: Tor Operator is a Kubernetes Operator that manages Onion Balances, Onion Keys and Onion Services to provide a highly available, load balanced and fault tolerate Tor Ingress and Tor Proxy.
site_name: Tor Operator
site_url: https://agabani.github.io/tor-operator/docs/
theme: readthedocs
