pre-release-replacements = [
  { file="charts/tor-operator/Chart.yaml", search="version: .*", replace="version: {{version}}" },
  { file="charts/tor-operator/Chart.yaml", search="appVersion: .*", replace="appVersion: \"{{version}}\"" },

  { file="docs/cli.md", search="--tag v.*", replace="--tag v{{version}}" },
  { file="README.md", search="--tag v.*", replace="--tag v{{version}}" },

  { file="CHANGELOG.md", search="Unreleased", replace="{{version}}" },
  { file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1 },
  { file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}" },
  { file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly=1 },
  { file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n\n[Unreleased]: https://github.com/agabani/tor-operator/compare/{{tag_name}}...HEAD", exactly=1 },
]
