apiVersion: tor.agabani.co.uk/v1
kind: OnionService
metadata:
  name: onion-service-{{ include "example.fullname" . }}-containers
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  deployment:
    containers:
      tor:
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      ubuntu:
        args:
          - -c
          - sleep infinity
        command:
          - /bin/bash
        image: ubuntu:latest
        imagePullPolicy: IfNotPresent
        env:
          HOST:
            value: "127.0.0.1"
          PORT:
            valueFrom:
              configMapKeyRef:
                name: onion-service-{{ include "example.fullname" . }}-containers-env
                key: port
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - echo > /dev/tcp/$${HOST}/$${PORT}
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - echo > /dev/tcp/$${HOST}/$${PORT}
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        startupProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - echo > /dev/tcp/$${HOST}/$${PORT}
  onionKey:
    name: onion-service-{{ include "example.fullname" . }}-containers
  ports:
    - target: example:80
      virtport: 80
