apiVersion: tor.agabani.co.uk/v1
kind: OnionService
metadata:
  name: onion-service-{{ include "example.fullname" . }}-containers
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  deployment:
    containers:
      - name: tor
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
          - name: tmp-shared
            mountPath: /tmp/shared
      - name: ubuntu
        args:
          - -c
          - sleep infinity
        command:
          - /bin/bash
        image: ubuntu:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: HOST
            value: "127.0.0.1"
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: onion-service-{{ include "example.fullname" . }}-containers-env
                key: port
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - echo > /dev/tcp/$${HOST}/$${PORT}
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - echo > /dev/tcp/$${HOST}/$${PORT}
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        startupProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - echo > /dev/tcp/$${HOST}/$${PORT}
        volumeMounts:
          - name: tmp-shared
            mountPath: /tmp/shared
    initContainers:
      - name: ubuntu-file
        args:
          - -c
          - echo "content" > /tmp/shared/file
        command:
          - /bin/bash
        image: ubuntu:latest
        volumeMounts:
          - name: tmp-shared
            mountPath: /tmp/shared
    volumes:
      - name: tmp-shared
        emptyDir:
          sizeLimit: 32Mi
  onionKey:
    name: onion-service-{{ include "example.fullname" . }}-containers
  ports:
    - target: example:80
      virtport: 80
