apiVersion: tor.agabani.co.uk/v1
kind: OnionService
metadata:
  name: onion-service-{{ include "example.fullname" . }}-torrc
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  deployment:
    containers:
      - name: tor
        env:
          - name: TOR_METRIC_PORT
            value: "127.0.0.1:9035"
          - name: TOR_METRIC_PORT_POLICY
            valueFrom:
              configMapKeyRef:
                name: onion-service-{{ include "example.fullname" . }}-torrc-env
                key: metrics_port_policy
  onionKey:
    name: onion-service-{{ include "example.fullname" . }}-torrc
  ports:
    - target: example:80
      virtport: 80
  torrc:
    template: |
      MetricsPort ${TOR_METRIC_PORT}
      MetricsPortPolicy ${TOR_METRIC_PORT_POLICY}
