apiVersion: tor.agabani.co.uk/v1
kind: OnionBalance
metadata:
  name: onion-balance-{{ include "example.fullname" . }}-full
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  config_map:
    name: onion-balance-{{ include "example.fullname" . }}-full
  deployment:
    name: onion-balance-{{ include "example.fullname" . }}-full
  onion_key:
    name: onion-balance-{{ include "example.fullname" . }}-full
  onion_services:
    - onion_key:
        hostname: 3evpjb3a5qxaubnzodlxlgn3ccp3achwwwtirgpznnl752oyg2oxekid.onion
