apiVersion: tor.agabani.co.uk/v1
kind: OnionBalance
metadata:
  name: onion-balance-{{ include "example.fullname" . }}-full
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  configMap:
    name: onion-balance-{{ include "example.fullname" . }}-full
  deployment:
    containers:
      onionBalance:
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      tor:
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
    name: onion-balance-{{ include "example.fullname" . }}-full
  onionKey:
    name: onion-balance-{{ include "example.fullname" . }}-full
  onionServices:
    - onionKey:
        hostname: 3evpjb3a5qxaubnzodlxlgn3ccp3achwwwtirgpznnl752oyg2oxekid.onion
