apiVersion: tor.agabani.co.uk/v1
kind: OnionBalance
metadata:
  name: onion-balance-{{ include "example.fullname" . }}-full
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  configMap:
    annotations:
      key-a-1: value-a-1
      key-a-2: value-a-2
    labels:
      key-l-1: value-l-1
      key-l-2: value-l-2
    name: onion-balance-{{ include "example.fullname" . }}-full
  deployment:
    annotations:
      key-a-3: value-a-3
      key-a-4: value-a-4
    containers:
      onionbalance:
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      tor:
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
    labels:
      key-l-3: value-l-3
      key-l-4: value-l-4
    name: onion-balance-{{ include "example.fullname" . }}-full
    securityContext:
      fsGroup: 2000
      runAsGroup: 3000
      runAsUser: 1000
  onionKey:
    name: onion-balance-{{ include "example.fullname" . }}-full
  onionServices:
    - onionKey:
        hostname: 3evpjb3a5qxaubnzodlxlgn3ccp3achwwwtirgpznnl752oyg2oxekid.onion
