apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-proxy-{{ include "example.fullname" . }}-inject
  labels:
    app.kubernetes.io/instance: tor-proxy-{{ include "example.fullname" . }}-inject
    app.kubernetes.io/name: tor-proxy-{{ include "example.fullname" . }}-inject
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: tor-proxy-{{ include "example.fullname" . }}-inject
      app.kubernetes.io/name: tor-proxy-{{ include "example.fullname" . }}-inject
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: tor-proxy-{{ include "example.fullname" . }}-inject
        app.kubernetes.io/name: tor-proxy-{{ include "example.fullname" . }}-inject
        proxy.tor.agabani.co.uk/inject: "true"
    spec:
      containers:
        - image: nginx:1.25.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: example
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      restartPolicy: Always
