apiVersion: tor.agabani.co.uk/v1
kind: TorIngress
metadata:
  name: tor-ingress-{{ include "example.fullname" . }}-full
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  horizontalPodAutoscaler:
    # behavior:
    name: tor-ingress-{{ include "example.fullname" . }}-full-11
    maxReplicas: 4
    minReplicas: 2
    # metrics:
  onionBalance:
    configMap:
      name: tor-ingress-{{ include "example.fullname" . }}-full-2
    deployment:
      containers:
        onionBalance:
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
        tor:
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      name: tor-ingress-{{ include "example.fullname" . }}-full-3
    name: tor-ingress-{{ include "example.fullname" . }}-full-4
    onionKey:
      name: tor-ingress-{{ include "example.fullname" . }}-full-0
  onionService:
    configMap:
      namePrefix: tor-ingress-{{ include "example.fullname" . }}-full-6
    deployment:
      containers:
        tor:
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      namePrefix: tor-ingress-{{ include "example.fullname" . }}-full-7
    namePrefix: tor-ingress-{{ include "example.fullname" . }}-full-8
    onionKey:
      namePrefix: tor-ingress-{{ include "example.fullname" . }}-full-9
      secret:
        namePrefix: tor-ingress-{{ include "example.fullname" . }}-full-10
    ports:
      - target: example:80
        virtport: 80
    replicas: 3
