apiVersion: v1
kind: ConfigMap
metadata:
  name: tor-ingress-{{ include "example.fullname" . }}-containers-env
  labels:
    {{- include "example.labels" . | nindent 4 }}
data:
  port: "9050"
