apiVersion: tor.agabani.co.uk/v1
kind: TorIngress
metadata:
  name: tor-ingress-{{ include "example.fullname" . }}-containers
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  onionBalance:
    deployment:
      containers:
        onionbalance:
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            tmp-shared:
              mountPath: /tmp/shared
        tor:
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            tmp-shared:
              mountPath: /tmp/shared
        ubuntu:
          args:
            - -c
            - sleep infinity
          command:
            - /bin/bash
          image: ubuntu:latest
          imagePullPolicy: IfNotPresent
          env:
            HOST:
              value: "127.0.0.1"
            PORT:
              valueFrom:
                configMapKeyRef:
                  name: tor-ingress-{{ include "example.fullname" . }}-containers-env
                  key: port
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - echo > /dev/tcp/$${HOST}/$${PORT}
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - echo > /dev/tcp/$${HOST}/$${PORT}
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          startupProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - echo > /dev/tcp/$${HOST}/$${PORT}
          volumeMounts:
            tmp-shared:
              mountPath: /tmp/shared
      volumes:
        tmp-shared:
          emptyDir:
            sizeLimit: 32Mi
    onionKey:
      name: tor-ingress-{{ include "example.fullname" . }}-containers
  onionService:
    deployment:
      containers:
        tor:
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            tmp-shared:
              mountPath: /tmp/shared
        ubuntu:
          args:
            - -c
            - sleep infinity
          command:
            - /bin/bash
          image: ubuntu:latest
          imagePullPolicy: IfNotPresent
          env:
            HOST:
              value: "127.0.0.1"
            PORT:
              valueFrom:
                configMapKeyRef:
                  name: tor-ingress-{{ include "example.fullname" . }}-containers-env
                  key: port
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - echo > /dev/tcp/$${HOST}/$${PORT}
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - echo > /dev/tcp/$${HOST}/$${PORT}
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          startupProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - echo > /dev/tcp/$${HOST}/$${PORT}
          volumeMounts:
            tmp-shared:
              mountPath: /tmp/shared
      volumes:
        tmp-shared:
          emptyDir:
            sizeLimit: 32Mi
    ports:
      - target: example:80
        virtport: 80
