apiVersion: tor.agabani.co.uk/v1
kind: OnionKey
metadata:
  name: tor-ingress-{{ include "example.fullname" . }}-deployment
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  autoGenerate: true
  secret:
    name: tor-ingress-{{ include "example.fullname" . }}-deployment
