apiVersion: tor.agabani.co.uk/v1
kind: TorIngress
metadata:
  name: tor-ingress-{{ include "example.fullname" . }}-deployment
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  onionBalance:
    deployment:
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsUser: 1000
    onionKey:
      name: tor-ingress-{{ include "example.fullname" . }}-deployment
  onionService:
    deployment:
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsUser: 1000
    ports:
      - target: example:80
        virtport: 80

