apiVersion: tor.agabani.co.uk/v1
kind: TorIngress
metadata:
  name: tor-ingress-{{ include "example.fullname" . }}-hpa-external
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  onionBalance:
    onionKey:
      name: tor-ingress-{{ include "example.fullname" . }}-hpa-external
  onionService:
    deployment:
      containers:
        - name: tor
          resources:
            requests:
              cpu: 100m
    ports:
      - target: example:80
        virtport: 80
