apiVersion: tor.agabani.co.uk/v1
kind: TorIngress
metadata:
  name: tor-ingress-{{ include "example.fullname" . }}-aln
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  horizontalPodAutoscaler:
    annotations:
      key-a-1: value-a-1
      key-a-2: value-a-2
    labels:
      key-l-1: value-l-1
      key-l-2: value-l-2
    maxReplicas: 4
    minReplicas: 2
    name: tor-ingress-{{ include "example.fullname" . }}-aln-11
  onionBalance:
    annotations:
      key-a-3: value-a-3
      key-a-4: value-a-4
    configMap:
      annotations:
        key-a-5: value-a-5
        key-a-6: value-a-6
      labels:
        key-l-5: value-l-5
        key-l-6: value-l-6
      name: tor-ingress-{{ include "example.fullname" . }}-aln-2
    deployment:
      annotations:
        key-a-7: value-a-7
        key-a-8: value-a-8
      labels:
        key-l-7: value-l-7
        key-l-8: value-l-8
      name: tor-ingress-{{ include "example.fullname" . }}-aln-3
    labels:
      key-l-3: value-l-3
      key-l-4: value-l-4
    name: tor-ingress-{{ include "example.fullname" . }}-aln-4
    onionKey:
      name: tor-ingress-{{ include "example.fullname" . }}-aln-0
  onionService:
    annotations:
      key-a-9: value-a-9
      key-a-10: value-a-10
    configMap:
      annotations:
        key-a-11: value-a-11
        key-a-12: value-a-12
      labels:
        key-l-11: value-l-11
        key-l-12: value-l-12
      namePrefix: tor-ingress-{{ include "example.fullname" . }}-aln-6
    deployment:
      annotations:
        key-a-13: value-a-13
        key-a-14: value-a-14
      containers:
        - name: tor
          resources:
            requests:
              cpu: 100m
      labels:
        key-l-13: value-l-13
        key-l-14: value-l-14
      namePrefix: tor-ingress-{{ include "example.fullname" . }}-aln-7
    labels:
      key-l-9: value-l-9
      key-l-10: value-l-10
    namePrefix: tor-ingress-{{ include "example.fullname" . }}-aln-8
    onionKey:
      annotations:
        key-a-15: value-a-15
        key-a-16: value-a-16
      labels:
        key-l-15: value-l-15
        key-l-16: value-l-16
      namePrefix: tor-ingress-{{ include "example.fullname" . }}-aln-9
      secret:
        annotations:
          key-a-17: value-a-17
          key-a-18: value-a-18
        labels:
          key-l-17: value-l-17
          key-l-18: value-l-18
        namePrefix: tor-ingress-{{ include "example.fullname" . }}-aln-10
    ports:
      - target: example:80
        virtport: 80
