apiVersion: tor.agabani.co.uk/v1
kind: TorProxy
metadata:
  name: tor-proxy-{{ include "example.fullname" . }}-aln
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  configMap:
    annotations:
      key-a-1: value-a-1
      key-a-2: value-a-2
    labels:
      key-l-1: value-l-1
      key-l-2: value-l-2
    name: tor-proxy-{{ include "example.fullname" . }}-aln-1
  deployment:
    annotations:
      key-a-3: value-a-3
      key-a-4: value-a-4
    containers:
      tor:
        resources:
          requests:
            cpu: 100m
    labels:
      key-l-3: value-l-3
      key-l-4: value-l-4
    name: tor-proxy-{{ include "example.fullname" . }}-aln-2
  horizontalPodAutoscaler:
    annotations:
      key-a-5: value-a-5
      key-a-6: value-a-6
    labels:
      key-l-5: value-l-5
      key-l-6: value-l-6
    maxReplicas: 4
    minReplicas: 2
    name: tor-proxy-{{ include "example.fullname" . }}-aln-3
  service:
    annotations:
      key-a-7: value-a-7
      key-a-8: value-a-8
    labels:
      key-l-7: value-l-7
      key-l-8: value-l-8
    name: tor-proxy-{{ include "example.fullname" . }}-aln-4
    ports:
      - name: http-tunnel-1
        port: 1080
        protocol: HTTP_TUNNEL
      - name: socks-1
        port: 9050
        protocol: SOCKS
      - name: http-tunnel-2
        port: 1081
        protocol: HTTP_TUNNEL
      - name: socks-2
        port: 9051
        protocol: SOCKS
