{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tor-operator.clusterRoleName" . }}
  labels:
    {{- include "tor-operator.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["tor.agabani.co.uk"]
    resources: ["onionbalances", "onionkeys", "onionservices"]
    verbs: ["list", "watch"]
  - apiGroups: ["tor.agabani.co.uk"]
    resources: ["onionkeys/status"]
    verbs: ["patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "list", "patch", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "list", "patch", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "patch", "watch"]
{{- end }}
