{{- if .Values.clusterRoleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tor-operator.clusterRoleBindingName" . }}
  labels:
    {{- include "tor-operator.labels" . | nindent 4 }}
  {{- with .Values.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  kind: ClusterRole
  name: {{ include "tor-operator.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name:  {{ include "tor-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
