apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tor-operator.fullname" . }}
  labels:
    {{- include "tor-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tor-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tor-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tor-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.env }}
            {{- range $name, $value := . }}
            - name: "{{ $name }}"
              {{- toYaml $value | nindent 14 }}
            {{- end }}
            {{- end }}
          args:
            - "controller"
            - "run"

            {{- if (((.Values.onionBalance).image).pullPolicy) }} # depreciated: use .Values.env.ONION_BALANCE_IMAGE_PULL_POLICY
            - "--onion-balance-image-pull-policy"
            - "{{ .Values.onionBalance.image.pullPolicy }}"
            {{- end }}

            {{- if (((.Values.onionBalance).image).repository) }} # depreciated: use .Values.env.ONION_BALANCE_IMAGE_REPOSITORY
            - "--onion-balance-image-repository"
            - "{{ .Values.onionBalance.image.repository }}"
            {{- end }}

            {{- if (((.Values.onionBalance).image).tag) }} # depreciated: use .Values.env.ONION_BALANCE_IMAGE_TAG
            - "--onion-balance-image-tag"
            - "{{ .Values.onionBalance.image.tag }}"
            {{- end }}

            - "--host"
            - "0.0.0.0"

            - "--port"
            - "{{ .Values.service.port }}"

            {{- if (((.Values.tor).image).pullPolicy) }} # depreciated: use .Values.env.TOR_IMAGE_PULL_POLICY
            - "--tor-image-pull-policy"
            - "{{ .Values.tor.image.pullPolicy }}"
            {{- end }}

            {{- if (((.Values.tor).image).repository) }} # depreciated: use .Values.env.TOR_IMAGE_REPOSITORY
            - "--tor-image-repository"
            - "{{ .Values.tor.image.repository }}"
            {{- end }}

            {{- if (((.Values.tor).image).tag) }} # depreciated: use .Values.env.TOR_IMAGE_TAG
            - "--tor-image-tag"
            - "{{ .Values.tor.image.tag }}"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
