{{- if .Values.customResourceDefinition.create -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: onionservices.tor.agabani.co.uk
  labels:
    {{- include "tor-operator.labels" . | nindent 4 }}
  {{- with .Values.customResourceDefinition.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  group: tor.agabani.co.uk
  names:
    categories: []
    kind: OnionService
    plural: onionservices
    shortNames: []
    singular: onionservice
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The hostname of the OnionService
      jsonPath: .status.hostname
      name: Hostname
      type: string
    - description: The hostname of the OnionBalance
      jsonPath: .spec.onionBalance.onionKey.hostname
      name: OnionBalance Hostname
      type: string
    - description: Human readable description of state
      jsonPath: .status.state
      name: State
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for OnionServiceSpec via `CustomResource`
        properties:
          spec:
            description: |-
              An `OnionService` is an abstraction of a Tor Onion Service.

              A Tor Onion Service is a service that can only be accessed over Tor. Running a Tor Onion Service gives your users all the security of HTTPS with the added privacy benefits of Tor.
            properties:
              configMap:
                description: Config Map settings.
                nullable: true
                properties:
                  name:
                    description: |-
                      Name of the Config Map.

                      Default: name of the OnionService
                    nullable: true
                    type: string
                type: object
              deployment:
                description: Deployment settings.
                nullable: true
                properties:
                  containers:
                    description: Containers of the Deployment.
                    nullable: true
                    properties:
                      tor:
                        description: Tor container.
                        nullable: true
                        properties:
                          resources:
                            description: Resources of the container.
                            nullable: true
                            properties:
                              limits:
                                description: Limits of the Resources.
                                nullable: true
                                properties:
                                  cpu:
                                    description: CPU quantity of the Limits.
                                    nullable: true
                                    type: string
                                  memory:
                                    description: Memory quantity of the Limits.
                                    nullable: true
                                    type: string
                                type: object
                              requests:
                                description: Requests of the Resources.
                                nullable: true
                                properties:
                                  cpu:
                                    description: CPU quantity of the Requests.
                                    nullable: true
                                    type: string
                                  memory:
                                    description: Memory quantity of the Requests.
                                    nullable: true
                                    type: string
                                type: object
                            type: object
                        type: object
                    type: object
                  name:
                    description: |-
                      Name of the Deployment.

                      Default: name of the OnionService
                    nullable: true
                    type: string
                type: object
              onionBalance:
                description: |-
                  OnionBalance the OnionService belongs to.

                  Default: nil / none / null / undefined.
                nullable: true
                properties:
                  onionKey:
                    description: OnionKey reference of the OnionBalance.
                    properties:
                      hostname:
                        description: |-
                          Hostname value of the OnionKey.

                          Example: "abcdefg.onion"
                        type: string
                    required:
                    - hostname
                    type: object
                required:
                - onionKey
                type: object
              onionKey:
                description: OnionKey settings.
                properties:
                  name:
                    description: Name of the OnionKey.
                    type: string
                required:
                - name
                type: object
              ports:
                description: Onion Service Hidden Service ports.
                items:
                  properties:
                    target:
                      description: |-
                        The target any incoming traffic will be redirect to.

                        Example: example.default.svc.cluster.local:80
                      type: string
                    virtport:
                      description: |-
                        The virtual port that the Onion Service will be using.

                        Example: 80
                      format: int32
                      type: integer
                  required:
                  - target
                  - virtport
                  type: object
                type: array
            required:
            - onionKey
            - ports
            title: '`OnionService`'
            type: object
          status:
            nullable: true
            properties:
              hostname:
                description: |-
                  OnionKey hostname.

                  The hostname is only populated once `state` is "running".
                nullable: true
                type: string
              state:
                description: |-
                  Human readable description of state.

                  Possible values:

                  - OnionKey not found - OnionKey hostname not found - running
                type: string
            required:
            - state
            type: object
        required:
        - spec
        title: OnionService
        type: object
    served: true
    storage: true
    subresources:
      status: {}
{{- end }}
