{{- if .Values.customResourceDefinition.create -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: onionbalances.tor.agabani.co.uk
  labels:
    {{- include "tor-operator.labels" . | nindent 4 }}
  {{- with .Values.customResourceDefinition.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  group: tor.agabani.co.uk
  names:
    categories: []
    kind: OnionBalance
    plural: onionbalances
    shortNames: []
    singular: onionbalance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The hostname of the OnionBalance
      jsonPath: .status.hostname
      name: Hostname
      type: string
    - description: The hostname of OnionServices
      jsonPath: .status.onionServices
      name: OnionServices
      type: number
    - description: Human readable description of state
      jsonPath: .status.state
      name: State
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for OnionBalanceSpec via `CustomResource`
        properties:
          spec:
            description: |-
              An `OnionBalance` is an abstraction of a Tor Onion Balance.

              Tor Onion Balance is the best way to load balance Tor Onion Services. The load of introduction and rendezvous requests gets distributed across multiple hosts while also increasing resiliency by eliminating single points of failure.
            properties:
              configMap:
                description: Config Map settings.
                nullable: true
                properties:
                  name:
                    description: |-
                      Name of the Config Map.

                      Default: name of the OnionBalance
                    nullable: true
                    type: string
                type: object
              deployment:
                description: Deployment settings.
                nullable: true
                properties:
                  containers:
                    description: Containers of the Deployment.
                    nullable: true
                    properties:
                      onionBalance:
                        description: Onion Balance container.
                        nullable: true
                        properties:
                          resources:
                            description: Resources of the container.
                            nullable: true
                            properties:
                              limits:
                                description: Limits of the Resources.
                                nullable: true
                                properties:
                                  cpu:
                                    description: CPU quantity of the Limits.
                                    nullable: true
                                    type: string
                                  memory:
                                    description: Memory quantity of the Limits.
                                    nullable: true
                                    type: string
                                type: object
                              requests:
                                description: Requests of the Resources.
                                nullable: true
                                properties:
                                  cpu:
                                    description: CPU quantity of the Requests.
                                    nullable: true
                                    type: string
                                  memory:
                                    description: Memory quantity of the Requests.
                                    nullable: true
                                    type: string
                                type: object
                            type: object
                        type: object
                      tor:
                        description: Tor container.
                        nullable: true
                        properties:
                          resources:
                            description: Resources of the container.
                            nullable: true
                            properties:
                              limits:
                                description: Limits of the Resources.
                                nullable: true
                                properties:
                                  cpu:
                                    description: CPU quantity of the Limits.
                                    nullable: true
                                    type: string
                                  memory:
                                    description: Memory quantity of the Limits.
                                    nullable: true
                                    type: string
                                type: object
                              requests:
                                description: Requests of the Resources.
                                nullable: true
                                properties:
                                  cpu:
                                    description: CPU quantity of the Requests.
                                    nullable: true
                                    type: string
                                  memory:
                                    description: Memory quantity of the Requests.
                                    nullable: true
                                    type: string
                                type: object
                            type: object
                        type: object
                    type: object
                  name:
                    description: |-
                      Name of the Deployment.

                      Default: name of the OnionBalance
                    nullable: true
                    type: string
                type: object
              onionKey:
                description: OnionKey settings.
                properties:
                  name:
                    description: Name of the OnionKey.
                    type: string
                required:
                - name
                type: object
              onionServices:
                description: OnionService part of the OnionBalance load balancing.
                items:
                  properties:
                    onionKey:
                      description: OnionKey reference of the OnionService.
                      properties:
                        hostname:
                          description: |-
                            Hostname value of the OnionKey.

                            Example: "abcdefg.onion"
                          type: string
                      required:
                      - hostname
                      type: object
                  required:
                  - onionKey
                  type: object
                type: array
            required:
            - onionKey
            - onionServices
            title: '`OnionBalance`'
            type: object
          status:
            nullable: true
            properties:
              hostname:
                description: |-
                  OnionKey hostname.

                  The hostname is only populated once `state` is "running".
                nullable: true
                type: string
              onionServices:
                description: Number of OnionServices.
                format: int32
                type: integer
              state:
                description: |-
                  Human readable description of state.

                  Possible values:

                  - OnionKey not found - OnionKey hostname not found - running
                type: string
            required:
            - onionServices
            - state
            type: object
        required:
        - spec
        title: OnionBalance
        type: object
    served: true
    storage: true
    subresources:
      status: {}
{{- end }}
