apiVersion: v1
kind: Service
metadata:
  name: {{ include "tor-operator.fullname" . }}
  labels:
    {{- include "tor-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.https.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "tor-operator.selectorLabels" . | nindent 4 }}
