{{- if .Values.customResourceDefinition.create -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: toringresses.tor.agabani.co.uk
  labels:
    {{- include "tor-operator.labels" . | nindent 4 }}
  {{- with .Values.customResourceDefinition.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  group: tor.agabani.co.uk
  names:
    categories: []
    kind: TorIngress
    plural: toringresses
    shortNames: []
    singular: toringress
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The hostname of the tor ingress
      jsonPath: .status.hostname
      name: Hostname
      type: string
    - description: Number of replicas
      jsonPath: .status.replicas
      name: Replicas
      type: number
    - description: Human readable description of state
      jsonPath: .status.state
      name: State
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for TorIngressSpec via `CustomResource`
        properties:
          spec:
            description: |-
              A `TorIngress` is collection of `OnionServices` load balanced by a `OnionBalance`.

              The user must provide the `OnionKey` for the `OnionBalance`.

              The Tor Operator will auto generate random `OnionKeys` for the `OnionServices`.
            properties:
              onionBalance:
                description: OnionBalance settings.
                properties:
                  configMap:
                    description: Config Map settings.
                    nullable: true
                    properties:
                      name:
                        description: |-
                          Name of the Config Map.

                          Default: name of the TorIngress
                        nullable: true
                        type: string
                    type: object
                  deployment:
                    description: Deployment settings.
                    nullable: true
                    properties:
                      containers:
                        description: Containers of the Deployment.
                        nullable: true
                        properties:
                          onionBalance:
                            description: Onion Balance container.
                            nullable: true
                            properties:
                              resources:
                                description: Resources of the container.
                                nullable: true
                                properties:
                                  limits:
                                    description: Limits of the Resources.
                                    nullable: true
                                    properties:
                                      cpu:
                                        description: CPU quantity of the Limits.
                                        nullable: true
                                        type: string
                                      memory:
                                        description: Memory quantity of the Limits.
                                        nullable: true
                                        type: string
                                    type: object
                                  requests:
                                    description: Requests of the Resources.
                                    nullable: true
                                    properties:
                                      cpu:
                                        description: CPU quantity of the Requests.
                                        nullable: true
                                        type: string
                                      memory:
                                        description: Memory quantity of the Requests.
                                        nullable: true
                                        type: string
                                    type: object
                                type: object
                            type: object
                          tor:
                            description: Tor container.
                            nullable: true
                            properties:
                              resources:
                                description: Resources of the container.
                                nullable: true
                                properties:
                                  limits:
                                    description: Limits of the Resources.
                                    nullable: true
                                    properties:
                                      cpu:
                                        description: CPU quantity of the Limits.
                                        nullable: true
                                        type: string
                                      memory:
                                        description: Memory quantity of the Limits.
                                        nullable: true
                                        type: string
                                    type: object
                                  requests:
                                    description: Requests of the Resources.
                                    nullable: true
                                    properties:
                                      cpu:
                                        description: CPU quantity of the Requests.
                                        nullable: true
                                        type: string
                                      memory:
                                        description: Memory quantity of the Requests.
                                        nullable: true
                                        type: string
                                    type: object
                                type: object
                            type: object
                        type: object
                      name:
                        description: |-
                          Name of the Deployment.

                          Default: name of the TorIngress
                        nullable: true
                        type: string
                    type: object
                  name:
                    description: |-
                      Name of the OnionBalance.

                      Default: name of the TorIngress
                    nullable: true
                    type: string
                  onionKey:
                    description: OnionKey settings.
                    properties:
                      name:
                        description: Name of the OnionKey.
                        type: string
                    required:
                    - name
                    type: object
                required:
                - onionKey
                type: object
              onionService:
                description: OnionService settings.
                properties:
                  configMap:
                    description: Config Map settings.
                    nullable: true
                    properties:
                      namePrefix:
                        description: |-
                          Name prefix of the Config Map.

                          Default: name of the TorIngress
                        nullable: true
                        type: string
                    type: object
                  deployment:
                    description: Deployment settings.
                    nullable: true
                    properties:
                      containers:
                        description: Containers of the Deployment.
                        nullable: true
                        properties:
                          tor:
                            description: Tor container.
                            nullable: true
                            properties:
                              resources:
                                description: Resources of the container.
                                nullable: true
                                properties:
                                  limits:
                                    description: Limits of the Resources.
                                    nullable: true
                                    properties:
                                      cpu:
                                        description: CPU quantity of the Limits.
                                        nullable: true
                                        type: string
                                      memory:
                                        description: Memory quantity of the Limits.
                                        nullable: true
                                        type: string
                                    type: object
                                  requests:
                                    description: Requests of the Resources.
                                    nullable: true
                                    properties:
                                      cpu:
                                        description: CPU quantity of the Requests.
                                        nullable: true
                                        type: string
                                      memory:
                                        description: Memory quantity of the Requests.
                                        nullable: true
                                        type: string
                                    type: object
                                type: object
                            type: object
                        type: object
                      namePrefix:
                        description: |-
                          Name prefix of the Deployment.

                          Default: name of the TorIngress
                        nullable: true
                        type: string
                    type: object
                  namePrefix:
                    description: |-
                      Name prefix of the OnionService.

                      Default: name of the TorIngress
                    nullable: true
                    type: string
                  onionKey:
                    description: OnionKey settings.
                    nullable: true
                    properties:
                      namePrefix:
                        description: |-
                          Name prefix of the OnionKey.

                          Default: name of the TorIngress
                        nullable: true
                        type: string
                      secret:
                        description: Secret settings.
                        nullable: true
                        properties:
                          namePrefix:
                            description: |-
                              Name prefix of the Secret.

                              Default: name of the TorIngress
                            nullable: true
                            type: string
                        type: object
                    type: object
                  ports:
                    description: Onion Service Hidden Service ports.
                    items:
                      properties:
                        target:
                          description: The target any incoming traffic will be redirect to.
                          type: string
                        virtport:
                          description: The virtual port that the Onion Service will be using.
                          format: int32
                          type: integer
                      required:
                      - target
                      - virtport
                      type: object
                    type: array
                  replicas:
                    default: 3
                    description: Number of replicas.
                    format: int32
                    type: integer
                required:
                - ports
                type: object
            required:
            - onionBalance
            - onionService
            title: '`TorIngress`'
            type: object
          status:
            nullable: true
            properties:
              conditions:
                description: |-
                  Represents the latest available observations of a deployment's current state.

                  ### Initialized

                  `Initialized`

                  ### OnionKey

                  `NotFound`, `HostnameNotFound`, `Ready`
                items:
                  description: Condition contains details for one aspect of the current state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: lastTransitionTime is the last time the condition transitioned from one status to another. This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating details about the transition. This may be an empty string.
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date with respect to the current state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier indicating the reason for the condition's last transition. Producers of specific condition types may define expected values and meanings for this field, and whether the values are considered a guaranteed API. The value should be a CamelCase string. This field may not be empty.
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              hostname:
                description: |-
                  OnionKey hostname.

                  The hostname is only populated once `state` is "running".
                nullable: true
                type: string
              labelSelector:
                default: ''
                description: Label selector the Horizontal Pod Autoscaler will use to collect metrics.
                type: string
              replicas:
                description: Number of replicas.
                format: int32
                type: integer
            required:
            - replicas
            type: object
        required:
        - spec
        title: TorIngress
        type: object
    served: true
    storage: true
    subresources:
      scale:
        labelSelectorPath: .status.labelSelector
        specReplicasPath: .spec.onionService.replicas
        statusReplicasPath: .status.replicas
      status: {}
{{- end }}
