apiVersion: v1
kind: Secret
metadata:
  name: onion-balance-{{ include "example.fullname" . }}-torrc-env
data:
  hashed_control_password: |
    {{ "16:E600ADC1B52C80BB6022A0E999A7734571A451EB6AE50FED489B72E3DF" | b64enc }}
