apiVersion: tor.agabani.co.uk/v1
kind: TorProxy
metadata:
  name: tor-proxy-{{ include "example.fullname" . }}-deployment
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  deployment:
    securityContext:
      fsGroup: 2000
      runAsGroup: 3000
      runAsUser: 1000
  service:
    ports:
      - name: http-tunnel
        port: 1080
        protocol: HTTP_TUNNEL
      - name: socks
        port: 9050
        protocol: SOCKS
