apiVersion: v1
kind: ConfigMap
metadata:
  name: tor-ingress-{{ include "example.fullname" . }}-torrc-env
  labels:
    {{- include "example.labels" . | nindent 4 }}
data:
  metrics_port_policy: accept 127.0.0.1
