---
apiVersion: v1
kind: Secret
metadata:
  name: tor-onionbalance-{{ include "example.fullname" . }}
data:
  hostname: |
    {{ .Files.Get "secrets/tor-onionbalance-example/hostname" | b64enc }}
  hs_ed25519_public_key: |
    {{ .Files.Get "secrets/tor-onionbalance-example/hs_ed25519_public_key" | b64enc }}
  hs_ed25519_secret_key: |
    {{ .Files.Get "secrets/tor-onionbalance-example/hs_ed25519_secret_key" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tor-onion-service-{{ include "example.fullname" . }}
data:
  hostname: |
    {{ .Files.Get "secrets/tor-onion-service-example/hostname" | b64enc }}
  hs_ed25519_public_key: |
    {{ .Files.Get "secrets/tor-onion-service-example/hs_ed25519_public_key" | b64enc }}
  hs_ed25519_secret_key: |
    {{ .Files.Get "secrets/tor-onion-service-example/hs_ed25519_secret_key" | b64enc }}
  ob_config: |
    {{ .Files.Get "secrets/tor-onion-service-example/ob_config" | b64enc }}
