apiVersion: v1
kind: Secret
metadata:
  name: onion-key-{{ include "example.fullname" . }}
data:
  hostname: |
    {{ .Files.Get "secrets/onionkey/hostname" | b64enc }}
  hs_ed25519_public_key: |
    {{ .Files.Get "secrets/onionkey/hs_ed25519_public_key" | b64enc }}
  hs_ed25519_secret_key: |
    {{ .Files.Get "secrets/onionkey/hs_ed25519_secret_key" | b64enc }}
