name: "CD: Post Release Documentation"
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release-documentation:
    name: "Release: Documentation"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Configure: Git"
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: "Toolchain: just"
        uses: extractions/setup-just@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Toolchain: Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: "Toolchain: ghp-import"
        run: pip3 install ghp-import
      - name: "Toolchain: Mkdocs"
        run: just mkdocs-install
      - name: "Build"
        run: just mkdocs-build
      - name: Deploy
        run: ghp-import site -p -x docs
