name: "CI: Kubernetes"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    name: "Docker: Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        software: ["onion-balance", "tor", "tor-operator"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Toolchain: Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Toolchain: just"
        uses: extractions/setup-just@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Docker: Build"
        run: just docker-build-${{ matrix.software }}
      - name: "Docker: Save"
        run: just docker-save-${{ matrix.software }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: agabani-${{ matrix.software }}.tar
          retention-days: 1

  helm-test:
    name: "Helm: Test"
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Toolchain: just"
        uses: extractions/setup-just@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Toolchain: kubectl"
        uses: azure/setup-kubectl@v3
      - name: "Toolchain: helm"
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Kubernetes: kind"
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: images
          path: .
      - name: "Docker: Load"
        run: just docker-load
      - name: "Kubernetes: Load"
        run: just kube-load
      - name: "Kubernetes: Test"
        run: just kube-test
