name: "Schedule: Cargo Deny"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  cargo-deny:
    name: "Cargo: Deny"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1
