---
apiVersion: tor.agabani.co.uk/v1
kind: OnionKey
metadata:
  name: onion-service-{{ include "example.fullname" . }}-onion-balance-onion-balance
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  auto_generate: true
  secret:
    name: onion-service-{{ include "example.fullname" . }}-onion-balance-onion-balance
---
apiVersion: tor.agabani.co.uk/v1
kind: OnionKey
metadata:
  name: onion-service-{{ include "example.fullname" . }}-onion-balance-onion-service
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  auto_generate: true
  secret:
    name: onion-service-{{ include "example.fullname" . }}-onion-balance-onion-service
