apiVersion: tor.agabani.co.uk/v1
kind: OnionService
metadata:
  name: onion-service-{{ include "example.fullname" . }}-onion-balance
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  onionBalance:
    onionKey:
      hostname: 3evpjb3a5qxaubnzodlxlgn3ccp3achwwwtirgpznnl752oyg2oxekid.onion
  onionKey:
    name: onion-service-{{ include "example.fullname" . }}-onion-balance
  ports:
    - target: example:80
      virtport: 80
